language: node_js

# See https://github.com/travis-ci/travis-ci/issues/6631 and https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty

node_js:
  - "6.9"

sudo: false

os:
  - linux

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CHROME_BIN=chromium-browser; fi  # Karma CI
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export DISPLAY=:99.0; fi

before_script:
  - npm install @angular/cli
  - ng build --prod
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sh -e /etc/init.d/xvfb start; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then nohup bash -c "webdriver-manager start 2>&1 &"; fi  # Protractor CI

after_failure:
  - cat /home/travis/build/mgechev/angular2-seed/npm-debug.log

notifications:
  email: true
  webhooks:
    urls: https://webhooks.gitter.im/e/565e4b2fed3b96c1b964
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

env:
  global:
    # https://github.com/DefinitelyTyped/tsd#tsdrc
    # Token has no scope (read-only access to public information)
    - TSD_GITHUB_TOKEN=9b18c72997769f3867ef2ec470e626d39661795d

cache:
  directories: node_modules

# script:
#   - npm run tests.all

# addons:
#   sonarcloud:
#     token:
#       secure: 266c9441629d0b29a2af8e8d9d9a2ed4833c0707
# script:
  # other script steps might be done before running the actual SonarQube analysis
  # - sonar-scanner
